rl_test:
    resource: "@RLTestBundle/Resources/config/routing.yml"
    prefix:   /

fp_js_form_validator:
    resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
    prefix: /fp_js_form_validator